[package]
name = "openzwave-rust-example"
version = "0.1.0"
authors = ["Julien Wajsberg <felash@gmail.com>"]

[dependencies]
"openzwave-stateful" = { git = "https://github.com/fxbox/openzwave-stateful-rust" }
env_logger = "0.3"
